version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.7.0
    working_directory: ~/my-app
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: 
          name: go_to_folder
          command: 'cd /home/circleci/project'
      - run: 
          name: Shipit_start
          command: 'shipit prod deploy'